Add missing include to fix build with clang-3.5 + Qt-5.4
/materialextension.cpp:74:24: error: must #include <typeinfo> before using typeid

(cherry picked from commit 0454a34f853d28ce4b80a00a075be89e32d1bff8)