Revert "fix compilation: error: 'intptr_t' has not been declared (include stdint.h)"
This reverts commit a61e7b5749841907ef94e0011f2bdd0fa7239a0a.

Still not compiling for me, even with this patch:

error: ‘INTPTR_MIN’ was not declared in this scope
error: ‘INTPTR_MAX’ was not declared in this scope

I wonder how this is supposed to work...