Fix compilation on ARM when building against Qt 4
  error: no matching function for call to 'qBound(qreal, double, qreal)'
  note: deduced conflicting types for parameter 'const T' ('float' and 'double')

It was happening because qreal 'is a typedef for float for performance reasons'
on ARM in Qt 4.