Add missing link target for qmljsdebugclient
The question is, why did that work for me in the past?

Trace:
/usr/bin/ld:
qmljsdebugclient/libqmldebugclient.a(qdeclarativedebugclient.cpp.o):
undefined reference to symbol 'QTcpSocket::QTcpSocket(QObject*)'
/usr/bin/ld: note: 'QTcpSocket::QTcpSocket(QObject*)' is defined in DSO
/usr/lib/gcc/x86_64-linux-gnu/4.6.1/../../../x86_64-linux-gnu/libQtNetwork.so
so try adding it to the linker command line
/usr/lib/gcc/x86_64-linux-gnu/4.6.1/../../../x86_64-linux-gnu/libQtNetwork.so:
could not read symbols: Invalid operation
collect2: ld returned 1 exit status