tests: Include Qt headers with -isystem
testhelpers.cpp was failing to build due to a warning in Qt:

    error: use of the 'assume' attribute is a C++23 extension
    [-Werror,-Wc++23-attribute-extensions]